# Generated by Django 3.1.2 on 2020-12-26 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Hitorial',
                'db_table': 'Historial',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('doctor', models.CharField(choices=[('Sofia Diaz', 'Sofia Diaz'), ('Raul Vallejos', 'Raul Vallejos')], max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor2Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('historial', models.ManyToManyField(null=True, related_name='histo', to='INGRESO.Historial')),
            ],
            options={
                'verbose_name': 'PacientesDoctor2',
                'verbose_name_plural': 'PacientesDoctor2',
                'db_table': 'PacientesDoctor2',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Doctor1Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('historial', models.ManyToManyField(blank=True, null=True, related_name='histor', to='INGRESO.Historial')),
            ],
            options={
                'verbose_name': 'PacientesDoctor1',
                'verbose_name_plural': 'PacientesDoctor1',
                'db_table': 'PacientesDoctor1',
                'ordering': ['apellido'],
            },
        ),
    ]
